### ISSUE TITLE
remove "community messages" if none

### ISSUE THREAD

**Issue by RFMoore** [IFRCGo/ecv-toolkit#20]
Currently the "Community Messages" header...

Community messages
See the follow community messages to support [action title]:

...appears at the bottom of each "Action" tool regardless of whether a Community Action is affiliated.  

Develop a script so if no community message, the community message header disappears

**Comment by danbjoseph** [comment]
fixed with 34c60c67a9d2f04ba0e989c771390da63c0a5fb8
although if the YAML metadata includes page(s) that don't exist, the section still appears
e.g. action 4 has `message: [24]` and there is no file for message 24 yet and it still renders like this with no links

-----
<img width="661" alt="screen shot 2018-07-23 at 8 21 07 pm" src="https://user-images.githubusercontent.com/4806884/43095394-fa4a6ea0-8eb5-11e8-93d2-8c5f485419ba.png">

-----
